name: E2B Sandbox Tests

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - unit
          - integration
          - security

jobs:
  e2b-sandbox-test:
    name: E2B Sandbox Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Configure E2B environment
      run: |
        echo "E2B_API_KEY=${{ secrets.E2B_API_KEY }}" >> .env
        echo "RESEND_API_KEY=test_key" >> .env
        echo "FROM_EMAIL=test@example.com" >> .env
        echo "PARTNER_EMAILS=partner@example.com" >> .env
    
    - name: Run E2B Sandbox Tests
      id: e2b-tests
      run: |
        echo "Starting E2B Sandbox tests..."
        npm run test:sandbox > test-output.log 2>&1
        TEST_EXIT_CODE=$?
        cat test-output.log
        echo "exit_code=$TEST_EXIT_CODE" >> $GITHUB_OUTPUT
        exit $TEST_EXIT_CODE
      continue-on-error: true
    
    - name: Parse Test Results
      if: always()
      run: |
        echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
        if [ -f test-output.log ]; then
          echo '```' >> $GITHUB_STEP_SUMMARY
          tail -n 50 test-output.log >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ "${{ steps.e2b-tests.outputs.exit_code }}" = "0" ]; then
          echo "✅ All tests passed!" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Some tests failed" >> $GITHUB_STEP_SUMMARY
        fi
    
    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: e2b-test-results
        path: |
          test-output.log
          coverage/
          test-results.json
        retention-days: 7
    
    - name: Notify on failure
      if: failure() && github.event_name == 'schedule'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'E2B Sandbox Tests Failed',
            body: `The scheduled E2B sandbox tests failed. Please check the [workflow run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.`,
            labels: ['bug', 'ci/cd']
          })

  performance-benchmark:
    name: Performance Benchmarking
    runs-on: ubuntu-latest
    needs: e2b-sandbox-test
    if: success()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run performance tests
      run: |
        echo "Running performance benchmarks..."
        time npm test -- --testNamePattern="Performance" || true
    
    - name: Generate performance report
      run: |
        echo "## Performance Metrics" >> $GITHUB_STEP_SUMMARY
        echo "- Test execution time: $(date)" >> $GITHUB_STEP_SUMMARY
        echo "- Node version: $(node -v)" >> $GITHUB_STEP_SUMMARY
        echo "- NPM version: $(npm -v)" >> $GITHUB_STEP_SUMMARY